export const FETCH_ZIPCODE_REQUEST = "FETCH_ZIPCODE_REQUEST";
export const FETCH_ZIPCODE_SUCCESS = "FETCH_ZIPCODE_SUCCESS";
export const FETCH_ZIPCODE_FAILURE = "FETCH_ZIPCODE_FAILURE";
export const UPDATE_SEARCH_HISTORY = "UPDATE_SEARCH_HISTORY";
